### ISSUE TITLE
Planejamento de telas no Figma

### ISSUE THREAD

**Issue by luzonni** [luzonni/somethingaboutbooks#4]
Planejamento e implementação de layout para usuarios. 

UX/UI

Link: https://www.figma.com/design/3rm4hU4qVI8MRzVC1ykfgZ/SAB?m=auto&t=EGFbNylyKIe3xSIR-1

**Comment by CaioRenatoDot** [comment]
Mais paginas serão feitas conforme outras forem finalizadas.

**Comment by CaioRenatoDot** [comment]
Telas concluidas, agora partindo para a produção do código, fazendo utilização do HTML CSS(Bootstrap) JS e React.
