### ISSUE TITLE
Implementação do layout

### ISSUE THREAD

**Issue by luzonni** [luzonni/somethingaboutbooks#5]
Implementação do layout no React.

**Comment by CaioRenatoDot** [comment]
Feita as telas: Login, Register, Pomodoro e Informações do Usuário.

**Comment by CaioRenatoDot** [comment]
Mais atualizações conforme a produção de mais telas.

**Comment by CaioRenatoDot** [comment]
Em andamento, 10 telas ja criadas, em suma falta a criacao das ultimas duas telas.
